Feature/cos 42
CosmoStarz/cosmostars pull request #10
Opened 2023-02-12 05:10 UTC by tacticSugar

### Реализованы игровые модели

### Необходимо реализовать столкновение выстрелов

2023-02-12 06:15 UTC, Sasha-meow requested changes
Все хорошо, все двигается и создается, к формату претензий особых нет
В дальнейшем, я думаю, нужно сделать общий класс для действующих объектов - Player и Enemy - они очень похожи. Но кажется, лучше создать новую задачу на это
Необходимо исправить несколько замечаний  - и аппрув)

2023-02-12 06:15 UTC, Sasha-meow commented on packages/client/src/entities/game/model/EnemyGrid/EnemyGrid.ts
> +      dx: 3,
Необходимо вынести все "волшебные" цифры в константы. Это касается и данной скорости, и цифр в колонках-строках сверху

2023-02-12 06:15 UTC, Sasha-meow commented on packages/client/src/entities/game/model/Enemy/Enemy.ts
> +      if (proj.position.y + proj.size.height >= this.scene.height) {
необходимо убрать `+ proj.size.height`, иначе пули пропадают чуть раньше конца поля, когда еще не дошли до границы

2023-02-12 06:15 UTC, Sasha-meow commented on packages/client/src/entities/game/model/EnemyGrid/EnemyGrid.ts
> +    return {
такая константа есть - initialCoords

2023-02-12 11:36 UTC, Sasha-meow commented on packages/client/src/App.tsx
> +
Я аппрувну, конечно, но лишние строки так и остались

2023-02-12 11:36 UTC, Sasha-meow approved these changes

2023-02-13 12:44 UTC, practicum-maxim-zyryanov requested changes
Классы действительно очень схожи с теми, которые уже существуют, да и магические числа продолжают встречаться. Предлагаю не откладывать архитектурные улучшения и исправить это сейчас.

2023-02-13 12:44 UTC, practicum-maxim-zyryanov commented on packages/client/src/entities/game/controller/Game.tsx
> +    this.randomInterval = Math.floor(Math.random() * 500 + 500);
Магические пятисотки, так просто и не разобрать зачем оно, в таких случаях выносим значения в константы и понятно обзываем

2023-02-13 12:44 UTC, practicum-maxim-zyryanov commented on packages/client/src/App.tsx
> +
Это определённо лишние строки. Они на Approve не влияют, но как минимум из-за магических чисел Approve не дам, поэтому давай поправим :)

2023-02-13 12:44 UTC, practicum-maxim-zyryanov commented on packages/client/src/entities/game/controller/Game.tsx
> +      this.randomInterval = Math.floor(Math.random() * 500 + 500);
И тут пятисотка...

2023-02-13 12:44 UTC, practicum-maxim-zyryanov commented on packages/client/src/entities/game/controller/Game.tsx
> +        if (this.frames % 100 === 0 && enemy.enemies.length > 0) {
А может быть и соточку вынести?

2023-02-15 13:26 UTC, Sasha-meow requested changes
1. Надо решить конфликт, пусть будет в сторону develop ветки
2. После правок все сломалось, что-то ты не то повыносил. Перед тем как заливать после внесения правок - нужно тщательно проверять

2023-02-15 16:28 UTC, Sasha-meow approved these changes
Ок, исправлено, класс вынесу в рамках [COS-68](https://linear.app/cosmostars/issue/COS-68/vynesti-klass-iz-player-i-enemy)

2023-02-15 18:37 UTC, practicum-maxim-zyryanov approved these changes
Approve, но генерацию рандомного интервала, встречающуюся пару раз, можно было и в функцию вынести

2023-02-15 20:35 UTC, merged