COS-15: Профиль
CosmoStarz/cosmostars pull request #11
Opened 2023-02-12 20:36 UTC by zomkd

### Какую задачу решаем
Сделал формы для изменения информации профиля (общая информация, пароль, аватар)

### TBD (если есть)
добавить API

2023-02-13 12:03 UTC, Sasha-meow commented
@zomkd , давай вмержим develop, а то проверять сложно

2023-02-14 13:52 UTC, Sasha-meow requested changes

2023-02-14 13:52 UTC, Sasha-meow commented on packages/client/src/widgets/Profile/Profile.tsx
> +            sx={{ display: "flex", flexDirection: "row" }}
Свойство `display: "flex"` по умолчанию предполагает `flex-direction: "row"` , давай уберем flexDirection

2023-02-14 13:52 UTC, Sasha-meow commented on packages/client/src/widgets/Profile/Profile.tsx
> +import Box from "@mui/material/Box";
Этот импорт ломает все, надо исправлять 100%. Импорт сделай также как Tab и Tabs

2023-02-14 13:52 UTC, Sasha-meow commented on packages/client/src/pages/ProfilePage/index.tsx
> +    <BasicLayout>
MainLayout необходимо использовать тут. Профиль должен быть с менюшкой)

2023-02-14 13:52 UTC, Sasha-meow commented on packages/client/src/features/Profile/change-avatar/ui.tsx
> +            <Avatar alt="avatar" sx={{ width: 202, height: 188 }} />
Эта вещь должна работать как превью после загрузки файлика, в комментах в фигме было указано. Делаем это сейчас или выносим в отдельную задачу?

2023-02-14 13:52 UTC, Sasha-meow commented on packages/client/src/features/Profile/change-avatar/ui.tsx
> +                  Click to upload <input type="file" hidden />
Давай сразу выставим свойство accept, как прописано в описании ниже? `accept="image/png, image/jpeg, image/jpg, image/svg, image/gif"`

2023-02-14 14:09 UTC, zomkd commented on packages/client/src/features/Profile/change-avatar/ui.tsx
> +// { handleChangeAvatar }: ChangeAvatarProps
комменты оставлены специально, как напоминание, где нужно добавить api методы

2023-02-14 14:13 UTC, zomkd commented on packages/client/src/router/Router.tsx
> +          <GuestMode>
пока нет апи, оставил так, чтобы была возможность просмотреть

2023-02-14 14:15 UTC, zomkd commented on packages/client/src/features/Profile/change-password/ui.tsx
> +import { PropsWithChildren } from "react";
эта легаси-страница-заглушка (не я ее делал) - удалил

2023-02-14 14:16 UTC, zomkd commented on packages/client/src/features/Profile/change-avatar/ui.tsx
> +            <Avatar alt="avatar" sx={{ width: 202, height: 188 }} />
отдельная задача

2023-02-14 14:17 UTC, Sasha-meow commented on packages/client/src/router/Router.tsx
> +          <GuestMode>
Проблема в том, что если ты авторизован - то ее не просмотришь(

2023-02-14 14:41 UTC, Sasha-meow commented on packages/client/src/features/Profile/change-avatar/ui.tsx
> +            <Avatar alt="avatar" sx={{ width: 202, height: 188 }} />
Создала

2023-02-14 15:19 UTC, zomkd commented on packages/client/src/features/Profile/change-profile/ui.tsx
> +      phone: "8800553535",
Мне так нагляднее будет, что тут тестовые константы, которые надо будет получать динамически

2023-02-14 16:08 UTC, Sasha-meow approved these changes
Умничка, разобрался с гитом и перепутанными коммитами

2023-02-14 16:08 UTC, Sasha-meow commented on packages/client/src/features/Profile/change-avatar/ui.tsx
> +              padding: "0",
MUI позволяет лаконично описывать стили, касающиеся отступов: вместо `padding: "0"` можно писать `p: 0`. [Тут](https://mui.com/system/spacing/) расписано более подробно о таких трюках
Это не замечание, просто информация на будущее)

2023-02-15 20:17 UTC, practicum-maxim-zyryanov approved these changes

2023-02-15 20:17 UTC, practicum-maxim-zyryanov commented on packages/client/src/features/Auth/schemas/sign-in/index.ts
> +import { ERROR_MESSAGES } from "../../../../shared/constants/error-messages";
Пути становятся всё больше, но можно настроить сокращения (для примера ссылка, но можно легко настроить и в рамках инструментов проекта)

https://javascript.plainenglish.io/how-to-shorten-import-paths-in-react-and-typescript-nodejs-5b257ee0c3fa

2023-02-15 20:17 UTC, practicum-maxim-zyryanov commented on packages/client/src/features/Profile/change-avatar/ui.tsx
> +// { handleChangeAvatar }: ChangeAvatarProps
Вот это и стоило отписать комментом рядом с комментом :) 
Это позволяет и другим определить, что комментарий оставлен сознательно и понимать, при каких обстоятельствах его убрать. А сейчас вполне может быть так, что решите добавлять API как-то иначе и коммент так и будет висеть.

2023-02-16 05:56 UTC, Sasha-meow commented on packages/client/src/features/Auth/schemas/sign-in/index.ts
> +import { ERROR_MESSAGES } from "../../../../shared/constants/error-messages";
Да, у нас [задача](https://linear.app/cosmostars/issue/COS-60/vnedrit-nastrojki-dlya-importov) уже заведена и отдана в разработку, в этом спринте будет готово)

2023-02-16 05:57 UTC, merged