COS-17: Форум
CosmoStarz/cosmostars pull request #12
Opened 2023-02-12 20:48 UTC by littox

### Какую задачу решаем
Добавлена страница со списком форумов

### TBD (если есть)
Добавить апи в следующих спринтах

2023-02-13 12:04 UTC, Sasha-meow commented
@littox давай вмержим develop, а то проверять сложно

2023-02-13 13:37 UTC, littox commented
@Sasha-meow подлил

> давай вмержим develop, а то проверять сложно

2023-02-13 13:55 UTC, ArtificialMan3000 reviewed
Вроде всё хорошо, но есть замечания по декомпозиции.

Ещё у меня это выглядит вот так
![image](https://user-images.githubusercontent.com/16936575/218480607-d616bca6-a5da-4e52-a5d6-1217a54d542b.png)
![image](https://user-images.githubusercontent.com/16936575/218480489-2e37a860-bb35-477c-9c93-0c32fee9d0a7.png)
Это я к тому, что на невысоком разрешении (у меня 1366х786) всё скомкивается и становится неудобным.
Сейчас это поправлено в моём пулреквесте (убрано ограничение по высоте экрана). Когда он смёрджится, надо будет здесь поправить (скорее всего просто убрать overflowY).

2023-02-13 14:03 UTC, Sasha-meow requested changes
Все хорошо, единственное, почему не аппрувнула - расстояние нужно поменьше сделать и центрировать по оси Х, а то глаз слишком режет
![image](https://user-images.githubusercontent.com/72806681/218478051-d051bbbc-ecb7-445c-8755-4d326d13397d.png)
Ну и еще по декомпозиции если накинуть - странное размещение модалки и кнопки в одном отдельном компоненте...обычно просто модалку выносят в таком случае

2023-02-13 14:03 UTC, Sasha-meow commented on packages/client/src/pages/ForumPage/ForumPage.tsx
> +                      <ArrowForward></ArrowForward>
Можно заменить одиночным `<ArrowForward />`

2023-02-14 07:14 UTC, Sasha-meow commented on packages/client/src/pages/ForumTopicPage/ForumTopicPage.tsx
>  };
Это была другая задача, не в рамках данной. Уже вмержена

2023-02-14 07:14 UTC, Sasha-meow approved these changes

2023-02-15 20:23 UTC, practicum-maxim-zyryanov approved these changes
Хорошо, но возникает всё больше очень схожих компонентов, в дальнейшем следует подумать о рефакторинге

2023-02-16 06:00 UTC, merged