[COS-55] Добавлен ReduxToolkit
CosmoStarz/cosmostars pull request #13
Opened 2023-02-15 15:06 UTC by littox

### Какую задачу решаем
Добавлен ReduxToolkit, в качесте примера запрашиваем пользователя.

https://linear.app/cosmostars/issue/COS-55/pervichnaya-nastrojka-redux

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-02-15 15:43 UTC, Sasha-meow requested changes
Все отлично, ты просто умница, все аккуратно, да и еще добавил пример использования! Огонь!
Единственное что - давай в useEffect вынесем этот метод, чтоб правильно было и отформатируем

2023-02-15 15:43 UTC, Sasha-meow commented on packages/client/src/app/index.tsx
> +  useGetUserInfoQuery();
Очень круто, что добавил пример и комментарий !
Но давай его засунем в useEffect тогда уж, вместо того левого метода, что там сейчас

2023-02-15 15:43 UTC, Sasha-meow commented on packages/client/src/app/store/types.d.ts
> +export type AppDispatch = AppStore['dispatch'];
Сделай yarn format перед тем, как будешь заливать - скобки разные везде

2023-02-15 20:25 UTC, practicum-maxim-zyryanov commented on packages/client/src/app/store/types.d.ts
> +export type AppDispatch = AppStore['dispatch'];
Думаю можно его попытаться настроить для автоматического запуска, часто всплывает эта проблема в команде

2023-02-16 15:24 UTC, Sasha-meow approved these changes

2023-02-16 15:25 UTC, Sasha-meow commented on packages/client/src/app/store/types.d.ts
> +export type AppDispatch = AppStore['dispatch'];
Завела задачку на рефактор, будем там настраивать

2023-02-16 17:17 UTC, practicum-maxim-zyryanov approved these changes

2023-02-16 18:10 UTC, merged