COS-43 - Обработка взаимодействия игровых объектов
CosmoStarz/cosmostars pull request #14
Opened 2023-02-17 12:19 UTC by Sasha-meow

### Обработка взаимодействия игровых объектов

[COS-43](https://linear.app/cosmostars/issue/COS-43/obrabotka-vzaimodejstviya-igrovyh-obuektov)

В рамках задачи реализовано:
1. Функция проверки столкновений разных объектов (игрок и вражеский снаряд, враг и снаряд игрока, столкновение двух снарядов, столкновение сетки врагов с игроком) - `checkCollisions()`
2. Функция, отслеживающая изменения размеров сетки врагов - `calculateNewWidth()`
3. Вынесла генерацию рандомного числа в отдельную функцию (лежит в папочке utils)
4. При проигрыше, т.е. если снаряд попал в игрока или сетка врагов врезалась в игрока, сделала функцию импровизированной паузы. После добавления состояний игры будет доработано, на это пока не смотрите особо)

### Видео

https://user-images.githubusercontent.com/72806681/219649635-bb0b409e-85a4-43cb-94d1-f830fff432d5.mp4

### Что будет дальше
1. В рамках задачи [COS-47](https://linear.app/cosmostars/issue/COS-47/dobavlenie-sostoyanij-igry) будут добавлены и обработаны состояния игры, будут выводиться соответствующие окошки
2. Рефактор некоторых классов игровых объектов (Player и Enemy) - вынес общего (задача уже в процессе, но заливать две задачи в один pr не стала, нехорошо будет)

2023-02-17 16:51 UTC, ArtificialMan3000 requested changes

2023-02-17 16:51 UTC, ArtificialMan3000 commented on packages/client/src/entities/game/controller/utils.ts
> +  Math.floor(Math.random() * max + min);
Функция работает неправильно. Она может выдавать числа больше max

2023-02-17 16:51 UTC, ArtificialMan3000 commented on packages/client/src/entities/game/controller/Game.tsx
> +      this.randomInterval = getRandomNumber(randomInterval, randomInterval);
Не пойму, в чём смысл брать число от 500 до 500. Или это временно так?

2023-02-17 16:51 UTC, ArtificialMan3000 commented on packages/client/src/entities/game/controller/Game.tsx
>          }, 0);
А почему здесь setTimeout на 0мс? Это какой-то хак?

2023-02-17 16:56 UTC, Sasha-meow commented on packages/client/src/entities/game/controller/utils.ts
> +  Math.floor(Math.random() * max + min);
Ну да, эта функция выдает рандомное число, тут смысл не в том, чтобы max было максимальным..для ясности могу просто переименовать эту переменную

2023-02-17 16:59 UTC, Sasha-meow commented on packages/client/src/entities/game/controller/Game.tsx
> +      this.randomInterval = getRandomNumber(randomInterval, randomInterval);
не ко мне вопрос, это не я автор этой функции, просто ее вынесла)
тут не от 500 до 500 берется, а от 500 и выше. Минимальное 500, а дальше как рандом сработает

2023-02-17 17:05 UTC, Sasha-meow commented on packages/client/src/entities/game/controller/Game.tsx
>          }, 0);
да, асинхронность

2023-02-17 17:08 UTC, ArtificialMan3000 commented on packages/client/src/entities/game/controller/Game.tsx
> +      this.randomInterval = getRandomNumber(randomInterval, randomInterval);
А зачем тогда два аргумента?

2023-02-17 17:08 UTC, ArtificialMan3000 commented on packages/client/src/entities/game/controller/utils.ts
> +  Math.floor(Math.random() * max + min);
Переименуй, а то непонятно пока...

2023-02-17 17:11 UTC, Sasha-meow commented on packages/client/src/entities/game/controller/Game.tsx
> +      this.randomInterval = getRandomNumber(randomInterval, randomInterval);
функция принимает два аргумента же) первый - коэффициент на который перемножить рандом (рандом же может быть не целым числом, с помощью коэффициента рандом можно сделать больше), а второй - минимальное число, с которого должно начинаться это рандомное число

2023-02-17 17:12 UTC, ArtificialMan3000 commented on packages/client/src/entities/game/controller/Game.tsx
> +      this.randomInterval = getRandomNumber(randomInterval, randomInterval);
Типа здесь получается от 500 до 1000?

2023-02-17 17:16 UTC, Sasha-meow commented on packages/client/src/entities/game/controller/Game.tsx
> +      this.randomInterval = getRandomNumber(randomInterval, randomInterval);
да

2023-02-17 17:16 UTC, Sasha-meow commented on packages/client/src/entities/game/controller/utils.ts
> +  Math.floor(Math.random() * max + min);
Переименовала

2023-02-17 17:25 UTC, ArtificialMan3000 commented on packages/client/src/entities/game/controller/utils.ts
> +  Math.floor(Math.random() * maxRatio + min);
Всё равно непонятно)) Если это диапазон возможных значений, может так и написать: range ? Ну а по-хорошему надо функцию, которая принимает min и max. И возвращает рандом между ними. Суть не изменится, а проще станет)

2023-02-17 17:29 UTC, Sasha-meow commented on packages/client/src/entities/game/controller/utils.ts
> +  Math.floor(Math.random() * maxRatio + min);
это не диапазон, а просто одно рандомное число. Такая функция - классика, вот даже ссылка на mdn 
![image](https://user-images.githubusercontent.com/72806681/219724064-4e0400da-da20-4423-93cc-e34ad1d675d6.png)

2023-02-17 17:34 UTC, ArtificialMan3000 commented on packages/client/src/entities/game/controller/utils.ts
> +  Math.floor(Math.random() * maxRatio + min);
На mdn это как раз максимальное число, до которого может быть рандом. А у нас это диапазон от min до максимального числа

2023-02-17 17:37 UTC, Sasha-meow commented on packages/client/src/entities/game/controller/utils.ts
> +  Math.floor(Math.random() * maxRatio + min);
Я немного не понимаю суть, а как надо-то?

2023-02-17 17:37 UTC, ArtificialMan3000 commented on packages/client/src/entities/game/controller/utils.ts
> +  Math.floor(Math.random() * maxRatio + min);
Не, ну можно и так оставить. Это наверное вопрос вкусовщины)

2023-02-17 17:42 UTC, ArtificialMan3000 commented on packages/client/src/entities/game/controller/utils.ts
> +  Math.floor(Math.random() * maxRatio + min);
Я предлагаю так

```suggestion
getRandom(min, max) {
  return Math.floor(Math.random() * (max - min) + min)
}
```

Получается число в промежутке от min до max

2023-02-17 17:54 UTC, Sasha-meow commented on packages/client/src/entities/game/controller/utils.ts
> +  Math.floor(Math.random() * maxRatio + min);
Переделала на твой способ, думаю так корректнее. Да и вообще, вдруг кому еще понадобится эта функция, чтоб сразу нормально работала)
Только еще единичку прибавила чтоб от max до min, включая обе величины считалось

2023-02-17 18:10 UTC, ArtificialMan3000 approved these changes

2023-02-19 20:14 UTC, practicum-maxim-zyryanov requested changes
Хорошо, но есть мелочи, которые рекомендовал бы сразу поправить

2023-02-19 20:14 UTC, practicum-maxim-zyryanov commented on packages/client/src/entities/game/controller/Game.tsx
> +      this.enemyGrids.push(this.createOneEnemyGrid);
Возможно не лучшее решение использовать здесь геттер, т.к. здесь он вводит в заблуждение, поскольку `createOneEnemyGrid` читается как функция, и от записи вида `this.enemyGrids.push(this.createOneEnemyGrid)` создается ощущение, что ты собираешь массив функций, которые будешь вызывать позднее. 

Здесь рекомендую воспользоваться именно записью вида `this.createOneEnemyGrid()`, а не заменять на что-то вроде `this.oneEnemyGrid`, т.к. это позволяет явно выразить намерение создавать новую сущность, а от геттера всё же ожидаешь, что тот ничего не создаёт, а лишь скрывает вычисление некоторого свойства объекта.

2023-02-19 20:14 UTC, practicum-maxim-zyryanov commented on packages/client/src/entities/game/controller/Game.tsx
> +  }
Слишком большой метод, плюс встречаются повторения, вместо выделения фрагментов комментариями предлагаю вынести фрагменты в отдельные функции, а может и описать для фрагментов одну более обобщенную функцию.

2023-02-19 20:14 UTC, practicum-maxim-zyryanov commented on packages/client/src/entities/game/controller/utils.ts
> +export const getRandomNumber = (max: number, min: number) =>
Не интуитивно, советую здесь поменять местами min и max

2023-02-20 03:58 UTC, Sasha-meow commented on packages/client/src/entities/game/controller/Game.tsx
> +  }
Я долго над этим думала, но что-то обобщенное написать так и не получилось, потому что они так или иначе чем-то различаются..

2023-02-20 06:33 UTC, practicum-maxim-zyryanov approved these changes

2023-02-20 06:37 UTC, practicum-maxim-zyryanov commented on packages/client/src/entities/game/controller/Game.tsx
> +  }
Согласен, меньше кода не стало, но теперь наглядно видно какие части кода важны и отличаются, а также при изменении стратегии обнаружения коллизий достаточно  будет внести изменения в одну часть кода

2023-02-20 06:55 UTC, merged