COS-53 - Реализовать передачу картинки в игровые объекты
CosmoStarz/cosmostars pull request #17
Opened 2023-02-21 20:07 UTC by tacticSugar

Добавлены картинки вместо квадратиков. 
Выключил lefthook на время. Не работает yarn в проекте из-за русской винды и именования папок на кириллице.

2023-02-22 06:39 UTC, Sasha-meow requested changes
Надо было хоть скриншот наведенной красоты добавить в описание, очень симпатично как по мне) Вот:
![image](https://user-images.githubusercontent.com/72806681/220540873-f895d8cf-c885-4901-b630-25dcedafb815.png)
Не аппрувну, как минимум волшебные строки вынести, пулю поправить и нужное в прекоммите раскомментировать надо..
По кириллице вижу несколько решений проблемы:
1. Найти какой-то обходной путь для этого. Вообще в будущем никогда не называй по-русски папки или что бы там не было...многие вещи могут ломаться из-за этого
2. Переименовать все-таки папку (но так как она корневая, будет проблематично, полагаю)
3. Переделать сборку на npm, но это как минимум надо с ребятами согласовывать, максимум - нужно время и свободный человек. У нас пока битком задач
Может, еще @practicum-maxim-zyryanov знает, как такое решить?

2023-02-22 06:39 UTC, Sasha-meow commented on lefthook.yml
> +# pre-commit:
Так, это мне вообще не нравится, прекоммит штука полезная, автоформат - тоже. Изначально хотя бы присутствовал блок с lint, его как минимум комментить не надо. Проблема с кириллицией - довольно распространенная, поэтому много где рекомендуют вообще с русским языком не связываться в названиях)

2023-02-22 06:39 UTC, Sasha-meow commented on packages/client/src/entities/game/controller/Game.tsx
> +      src: "game-model-player",
Волшебные строки надо вынести

2023-02-22 06:39 UTC, Sasha-meow commented on packages/client/src/entities/game/model/ShootingObject/ShootingObject.ts
> +        x: this.position.x + this.size.width / 2.5,
Ты задавался вопросом, почему деление на 2 криво выводит картинку - картинка пули кривая, еще раз скопируй её ровно прям по границам. Просто если это оставим и в дальнейшем захотим заменить картинку - она будет не посередине и съедет
Там в картинке ничего особенного, можно было вообще прямоугольником отрисовать

2023-02-22 06:39 UTC, Sasha-meow commented on packages/client/src/entities/game/model/BaseObject/BaseObject.tsx
> +    this.image.src = `/src/assets/images/${this.src}.png`;
не знаю даже ок привязываться прям к пути и строке src или нет...если поменяем путь - придется сюда лезть и менять. Если поменяем название картинки - нужно будет искать по всему проекту эти названия и менять на новые (т.к. нет enum). Как минимум нужно вынести все строки в enum, и из этой строки сделать какую-нибудь вспомогательную функцию
Но я б вообще сделала какой-нибудь enum нужных картинок, импортированных по типу `import PlayerTmage from "путь до файла"`. При изменении пути или названии файлика - нужно будет менять инфу в одном месте: только в самой строке импорта

2023-02-22 06:39 UTC, Sasha-meow commented on packages/client/src/entities/game/model/ShootingObject/ShootingObject.ts
> +import { projectileSize } from "../../../../shared/constants";
Давай короткий путь пропишем с `@/shared`

2023-02-22 11:18 UTC, tacticSugar commented on lefthook.yml
> +# pre-commit:
На след неделе будет новый ноут. На этом менять имя папки или переустанавливать винду не буду.

2023-02-22 11:18 UTC, tacticSugar commented on packages/client/src/entities/game/controller/Game.tsx
> +      src: "game-model-player",
+

2023-02-22 11:19 UTC, tacticSugar commented on packages/client/src/entities/game/model/ShootingObject/ShootingObject.ts
> +        x: this.position.x + this.size.width / 2.5,
Картинка новая, все равно рендерит чуть правее. Не понял, в чем проблема

2023-02-22 11:20 UTC, tacticSugar commented on packages/client/src/entities/game/model/ShootingObject/ShootingObject.ts
> +import { projectileSize } from "../../../../shared/constants";
+

2023-02-22 14:05 UTC, Sasha-meow commented on packages/client/src/entities/game/model/BaseObject/BaseObject.tsx
> +    this.image.src = `/src/assets/images/${this.src}.png`;
То, что путь так захардкожен мне все равно не нравится..но ок, пропущу дальше

2023-02-22 14:09 UTC, Sasha-meow commented on packages/client/src/entities/game/model/ShootingObject/ShootingObject.ts
> +        x: this.position.x + this.size.width / 2.5,
Проблема в том, что эта позиция задает начальную координату отрисовки по оси X, поэтому отсюда еще нужно вычесть половину ширины этой картинки

2023-02-24 12:31 UTC, Sasha-meow approved these changes

2023-02-25 07:28 UTC, practicum-maxim-zyryanov approved these changes

2023-02-25 08:53 UTC, merged