COS-56: api авторизации и логина
CosmoStarz/cosmostars pull request #18
Opened 2023-02-21 20:48 UTC by zomkd

### Какую задачу решаем
добавил yandex api к авторизации и регистрации

### Скриншоты/видяшка (если есть)

### TBD (если есть)
добавление OAuth

2023-02-22 14:11 UTC, Sasha-meow commented
Давай сначала вмержим дев и порешаем конфликты

2023-02-22 16:53 UTC, Sasha-meow requested changes
Проделана большая работа, ты умничка. Есть пара моментов, которые нужно поправить

2023-02-22 16:53 UTC, Sasha-meow commented on packages/client/src/app/store/index.ts
> +import { authModel } from "../../entities/auth";
Абсолютные пути надо поменять на относительные, когда вольешь сюда девелоп

2023-02-22 16:53 UTC, Sasha-meow commented on packages/client/src/app/store/index.ts
> +    getDefaultMiddleware().concat(authApi.auth.authApi.middleware),
Ооооочень большая вложенность и совершенно ненужная. Я думаю, ее можно избежать импортировав второй authApi) Получится вот так `import { authApi } from "../../shared/api/auth/auth";`

2023-02-22 16:53 UTC, Sasha-meow commented on packages/client/src/app/store/index.ts
> +    [authApi.auth.authApi.reducerPath]: authApi.auth.authApi.reducer,
если редьюсеров несколько - удобно пользоваться специальной функцией combineReducers. Это необязательно, конечно

2023-02-22 16:53 UTC, Sasha-meow commented on packages/client/src/features/Auth/SignUp/ui.tsx
> +      //TODO мне не нравится как это выглядит, принимаю предложение на улучшение
Как вариант - можно вынести эту функцию отдельно, она будет как конвертер: принимать данные, конвертировать в нужный формат и возвращать этот нужный формат. А сюда передать эту функцию и кинуть в нее values

2023-02-22 16:53 UTC, Sasha-meow commented on packages/client/src/pages/sign-in/index.tsx
> +  const handleSignIn = userForm => {
Необходимо типизировать userForm

2023-02-22 16:53 UTC, Sasha-meow commented on packages/client/src/shared/api/auth/auth.ts
> +  SIGN_IN = "/auth/signin",
тут повторяется auth - думаю можно вынести в отдельную константу

2023-02-22 16:53 UTC, Sasha-meow commented on packages/client/src/pages/sign-in/index.tsx
> +    }
Круто, что отлавливаешь ошибки! Но лучше вынести этот метод вместе с try...catch в отдельную функцию. Можно даже в хук useAuth засунуть и оттуда сюда передавать) а то слишком много логики в одном компоненте плодим (которую можно повыносить и код станет почище и попонятнее)
Та же история с sign up

2023-02-22 16:53 UTC, Sasha-meow commented on packages/client/src/features/Auth/SignUp/ui.tsx
> +      //TODO мне не нравится как это выглядит, принимаю предложение на улучшение
+ тут необходимо сделать обработку ошибок и вынести всю эту красоту

2023-02-22 16:53 UTC, Sasha-meow commented on packages/client/src/shared/api/auth/base.ts
> +      headers.set("authorization", `Bearer 1`);
Почему здесь ставится Bearer 1? Это весьма странно

2023-02-23 10:51 UTC, zomkd commented on packages/client/src/app/store/index.ts
> +    getDefaultMiddleware().concat(authApi.auth.authApi.middleware),
тут надо подумать как лучше отдельно (возможно при глобальном рефакторинге). По методологии FSD должен быть общий  publicAPI у слайса. Поэтому сделал вот так

2023-02-23 11:02 UTC, ArtificialMan3000 requested changes

2023-02-23 11:02 UTC, ArtificialMan3000 commented on packages/client/src/shared/api/auth/auth.ts
> +    }),
Почему-то при авторизации запрос на signIn происходит много раз.
![image](https://user-images.githubusercontent.com/16936575/220888152-686e6796-bb04-4d96-9527-460ec0dc29d9.png)

2023-02-23 11:10 UTC, ArtificialMan3000 commented on packages/client/src/shared/api/auth/base.ts
> +      headers.set("authorization", `Bearer 1`);
Врядли будет время для реализации регистрации на бекенде. Да и зачем, если это уже есть в апи?)

2023-02-23 11:59 UTC, Sasha-meow commented on packages/client/src/app/store/index.ts
> +    getDefaultMiddleware().concat(authApi.auth.authApi.middleware),
ну, общий никуда и не убежит, он есть и все хорошо. Просто второй authApi у тебя экспортирован, его можно указать напрямую

2023-02-26 13:33 UTC, ArtificialMan3000 requested changes
Пару маленьких моментов поправить

2023-02-26 13:33 UTC, ArtificialMan3000 commented on packages/client/src/app/store/index.ts
> +    [authApi.auth.authApi.reducerPath]: authApi.auth.authApi.reducer,
Здесь уже authApi не надо добавлять, можно yandexApi оставить, они на один и тотже reducerPath ссылаются

2023-02-26 13:33 UTC, ArtificialMan3000 commented on packages/client/src/app/store/index.ts
> +    getDefaultMiddleware().concat(authApi.auth.authApi.middleware),
Здесь тоже надо поменять на yandexApi. Все 'инжектированные апи' всё равно ссылаются на его мидлвару.

2023-02-26 13:33 UTC, ArtificialMan3000 commented on packages/client/src/pages/sign-up/index.tsx
> +    if (response.data?.id) {
Здесь тайпскрипт ругается. Поправь лучше сейчас, а то тесты из другого ПР валятся на это)

2023-02-26 18:35 UTC, Sasha-meow commented on packages/client/src/features/Auth/SignIn/ui.tsx
> +        password: values.password,
Думаю конкретно здесь можно просто отослать values

2023-02-26 18:35 UTC, Sasha-meow commented on packages/client/src/pages/sign-in/index.tsx
> +    if (response.error?.data === "OK") {
Ошибка типизации
![image](https://user-images.githubusercontent.com/72806681/221429549-1aa9a319-5e6b-4c4b-9999-2552a4bfa74e.png)

2023-02-26 18:35 UTC, Sasha-meow commented on packages/client/src/pages/sign-up/index.tsx
> +    if (response.data?.id) {
Может, и ненужный консоль лог уберем?

2023-02-27 11:39 UTC, Sasha-meow approved these changes

2023-02-27 11:46 UTC, ArtificialMan3000 approved these changes

2023-03-05 10:24 UTC, practicum-maxim-zyryanov approved these changes

2023-03-05 14:51 UTC, merged