[COS-61]: Добавлены звуки в игру (Web Audio API)
CosmoStarz/cosmostars pull request #24
Opened 2023-02-28 17:17 UTC by littox

2023-03-01 11:45 UTC, ArtificialMan3000 requested changes
Всё огонь, но найден баг (или это фича я хз)). Когда играешь без звука, проигрываешь и затем в окошке включаешь звук, проигрывается какой-то звук, которого, я предполагаю, быть не должно. Он похож на одновременный звук выстрела и взрыва.

2023-03-02 05:16 UTC, Sasha-meow requested changes
Очень круто, мне нравится! Музыка огонь! У меня особых замечаний нет, но надо исправить баг выше и волшебные строки

2023-03-02 05:16 UTC, Sasha-meow commented on packages/client/src/entities/game/ui/Sound/BufferLoader.ts
> +    request.open("GET", url, true);
Enum HTTPMethods с названием методов у нас есть по адресу \shared\api\types.ts. Предлагаю избавиться от волшебной строки и оттуда импортировать get

2023-03-02 05:16 UTC, Sasha-meow commented on packages/client/src/entities/game/ui/Sound/Sound.ts
> +    this.playSound("shot");
Давай эти все эти строки (данная и ниже) тоже вынесем в enum

2023-03-05 16:00 UTC, zomkd commented on packages/client/src/entities/game/ui/Sound/BufferLoader.ts
> +    let key: keyof GameSounds;
вместо let, можно использовать const

2023-03-05 16:40 UTC, littox commented on packages/client/src/entities/game/ui/Sound/BufferLoader.ts
> +    let key: keyof GameSounds;
тогда ниже будет Cannot assign to 'key' because it is a constant.

2023-03-05 17:07 UTC, Sasha-meow approved these changes

2023-03-05 18:10 UTC, ArtificialMan3000 approved these changes

2023-03-07 04:46 UTC, merged