COS-22 Добавлено сохранени состояние игры
CosmoStarz/cosmostars pull request #26
Opened 2023-03-02 16:21 UTC by tacticSugar

### Добавлен persistor, все сохраняется

TBD: задача на обработку канваса в зависимости от статуса

2023-03-03 04:21 UTC, Sasha-meow commented
Ошибка вот такая, надо фиксить
![image](https://user-images.githubusercontent.com/72806681/222630518-02824ba9-449f-4593-a693-ee4b6d232a62.png)

2023-03-05 12:53 UTC, ArtificialMan3000 requested changes
Привет. Несколько замечаний и package-lock надо удалить, т.к. работаем через yarn.
По поводу ошибки выше, посмотри вот это https://redux-toolkit.js.org/api/serializabilityMiddleware. Надо настроить мидлвару, чтобы она игнорировала экшн редакс персиста.

2023-03-05 12:53 UTC, ArtificialMan3000 commented on packages/client/src/app/store/index.ts
> +    game: reducer,
Здесь лучше назвать как-нибудь persistGameReducer, например. А то reducer - слишком общее название. Он же не один здесь редюсер.

2023-03-05 12:53 UTC, ArtificialMan3000 commented on packages/client/src/entities/game/controller/Game.tsx
> +    console.log("updated");
Надо убрать спамящий консоль лог.

2023-03-05 12:53 UTC, ArtificialMan3000 commented on packages/client/src/entities/game/ui/Canvas/Canvas.tsx
> +    this.context.font = "bold 32px Arial";
Вынести в константу

2023-03-05 17:16 UTC, Sasha-meow approved these changes

2023-03-05 17:45 UTC, ArtificialMan3000 requested changes

2023-03-05 17:45 UTC, ArtificialMan3000 commented on packages/client/src/app/store/index.ts
> +    getDefaultMiddleware({ serializableCheck: false }).concat(
Не надо полностью отключать мидлвару. Надо настройки указать. А конкретно вот так

```suggestion
    getDefaultMiddleware({ serializableCheck: {
        ignoredActions: ['persist/PERSIST']
    } }).concat(
```

2023-03-05 17:58 UTC, ArtificialMan3000 approved these changes

2023-03-05 19:40 UTC, merged