COS-59: HOC авторизации
CosmoStarz/cosmostars pull request #27
Opened 2023-03-04 19:55 UTC by zomkd

### Какую задачу решаем
добавил HOC для проверки авторизации пользователя

2023-03-05 17:03 UTC, Sasha-meow requested changes
Кое- что надо поправить, но все работает и это очень радует)

2023-03-05 17:03 UTC, Sasha-meow commented on packages/client/src/shared/hooks/useAuth.ts
> +    if ((data as unknown as SignInResponse).error.data === "OK") {
Нашла [решение](https://redux-toolkit.js.org/rtk-query/usage/mutations#frequently-used-mutation-hook-return-values) этой проблемы
Чтобы обойтись без таких танцев с бубном для мутаций надо использовать `.unwrap()` - обрабатывает результат вызова мутации и отдает status и data
Получится следующее `const { data } = await signUp(userForm).unwrap();`

2023-03-05 18:24 UTC, zomkd commented on packages/client/src/shared/hooks/useAuth.ts
> +    if ((data as unknown as SignInResponse).error.data === "OK") {
я пробовал unwrap() возвращал ошибку. Как я понял, ему не понравился формат, который возвращает апи яндекса

2023-03-05 19:54 UTC, zomkd commented on packages/client/src/shared/hooks/useAuth.ts
> +    isLoadingAuth,
все кроме isLoadingAuth используется

2023-03-06 04:35 UTC, Sasha-meow commented on packages/client/src/shared/hooks/useAuth.ts
> +    isLoadingAuth,
Я его и имею ввиду, он нигде не используется

2023-03-06 08:19 UTC, ArtificialMan3000 commented on packages/client/src/shared/hooks/useAuth.ts
> +    if ((data as unknown as SignInResponse).error.data === "OK") {
А зачем тут вобще вручную получать данные из триггера? Они же приходят из хука useSigninMutation (вторым аргументом в массиве). Там и data и error и всё что нужно

2023-03-06 09:04 UTC, Sasha-meow commented on packages/client/src/shared/hooks/useAuth.ts
> +    if ((data as unknown as SignInResponse).error.data === "OK") {
Проблема тут в том, что невалидный формат данных приходит с апи, поэтому тут только костылями обработаешь. Всегда возвращать будет error

2023-03-06 10:37 UTC, Sasha-meow commented on packages/client/src/shared/hooks/useAuth.ts
> +    if ((data as unknown as SignInResponse).error.data === "OK") {
Вот настройки парсинга https://redux-toolkit.js.org/rtk-query/api/fetchBaseQuery#parsing-a-response, мб они помогут

2023-03-06 21:33 UTC, zomkd commented on packages/client/src/shared/hooks/useAuth.ts
> +    isLoadingAuth,
> Я его и имею ввиду, он нигде не используется

просто помечено несколько было

2023-03-07 18:02 UTC, zomkd commented on packages/client/src/shared/hooks/useAuth.ts
> +    // сделан костыль т.к яндекс возвращает строку ОК на успех
выглядит классно!
только грустно, что само решение это костыль на костыль

2023-03-07 18:52 UTC, Sasha-meow approved these changes

2023-03-08 03:18 UTC, practicum-maxim-zyryanov approved these changes

2023-03-08 06:41 UTC, merged