Feature/cos 13 routing
CosmoStarz/cosmostars pull request #3
Opened 2023-02-04 17:37 UTC by ArtificialMan3000

### Какую задачу решаем
1. Написаны тесты для роутера
2. Написаны тесты для страниц
3. Созданы заглушки всех страниц
4. Добавлены роуты для всех страниц

Пулреквест пока в драфте, т.к. планирую ещё добавить приватный роутинг.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-02-06 17:05 UTC, Sasha-meow requested changes
Была проделана очень большая работа, ты молодец! В целом все очень аккуратненько.
Но есть пара моментов:
1. Реализация вышла далековато за рамки задачи. Но это мы с тобой уже обсуждали
2. К сожалению не подтянулся номер из линера( префикс некорректный, видимо.
И еще несколько вопросо-замечаний

2023-02-06 17:05 UTC, Sasha-meow commented on packages/client/src/router/modes/GuestMode/GuestMode.tsx
> +export const GuestMode: FC<PrivateModeProps> = ({ children }) => {
Мне, честно говоря, кажется, что мы можем обойтись одним PrivateMode...и реализовать его через hoc в связке с useAuth. На данный момент, из-за того, что у нас два таких похожих компонента Mode рендер происходит по два раза.
Но это уже будущая задача :)

2023-02-07 11:21 UTC, ArtificialMan3000 commented on packages/client/src/pages/GamePage/GamePage.test.tsx
> +  it("should have correct header", () => {
Это тест уже больше не на роутинг, а на саму страницу) Я пока не нашёл как проверять подключение самого компонента без поиска конкретных элементов в отрендеренном DOM.  Ещё посмотрю. Но здесь тест именно на хедер, т.к. он должен быть на странице по правилам доступности) Он может быть и визуально скрыт (есть такой класс sr-only для визуального скрытия элементов). А текст взял из макета, но можно к нему и не привязываться.
Вобще я тесты написал, т.к. пробовал по TDD сделать)) Написать тест для того, что должно быть, а потом это реализовать.

2023-02-07 11:26 UTC, ArtificialMan3000 commented on packages/client/src/pages/LeaderboardPage/LeaderboardPage.test.tsx
> +import { render, screen } from '@testing-library/react';
Сделал

2023-02-07 11:41 UTC, ArtificialMan3000 commented on packages/client/src/router/modes/GuestMode/GuestMode.tsx
> +    <Navigate to={RoutesName.PROFILE} replace={true} />
Поменял

2023-02-07 11:49 UTC, ArtificialMan3000 commented on packages/client/src/features/auth/logIn.ts
> +export const logIn = () => localStorage.setItem("isLogged", "1");
Вынес

2023-02-07 11:49 UTC, ArtificialMan3000 commented on packages/client/src/router/Router.tsx
> +      <Route path={RoutesName.GAME} element={<GamePage />} />
Добавил

2023-02-07 16:29 UTC, Sasha-meow commented on packages/client/src/pages/GamePage/GamePage.test.tsx
> +  it("should have correct header", () => {
Я все-таки считаю, что не нужно к тексту привязываться. Это как волшебные строки - может выстрелить в дальнейшем. Лучше всего посоветоваться с Максимом, чтобы он корректное решение подсказал) @practicum-maxim-zyryanov , нужен твой совет!
TDD - это конечно интересно, но у нас модуль командной разработки: если все будут разрабатывать, опираясь на разные методологии и не предупреждая друг друга - будет настоящий хаос. Наша цель сейчас - работать максимально синхронизировано и сообща, поэтому давай в следующий раз предупреждать нас (или хотя бы меня), если захочешь сделать больше функционала/декомпозировать задачи/добавить задачи. Кусаться никто не будет, все решим и все будут счастливы :)

2023-02-07 17:13 UTC, Sasha-meow approved these changes
Вопрос остался только с тестами

2023-02-07 18:42 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/GamePage/GamePage.test.tsx
> +  it("should have correct header", () => {
Т.к. тест называется "should have correct header", то здесь всё отлично, тест действительно проверяет именно это. Круто и то, что здесь учитываются правила доступности и упомянут sr-only тег. А использовать ли TDD - личное дело каждого, т.к это не аффектит на остальных, и если по времени успеваешь, то отлично, не стану останавливать.

Но здесь поддержу опасения @Sasha-meow, что "не нужно к тексту привязываться", т.к. строки слишком подвержены изменениям, а приложение может и мультиязычность поддерживать, то всё это гарантирует, что тест придётся часто менять. 

Но т.к. "тест не на роутинг", "а именно на хедер, т.к. он должен быть на странице по правилам доступности", то с точки зрения теста всё отлично, и даже правильно, что например использован метод getByText, вместо getByTestId, использованного в других тестах в пулреквесте.

Но вот тут вновь поддержу @Sasha-meow и спрошу, а вы обговорили командой поддерживать такой уровень доступности? И если нет, то @Sasha-meow права, не стоит придумывать себе задачи.

@ArtificialMan3000, классно, что учитываешь такие моменты и пробуешь новое, но в данном случае это то, что называют "нефункциональными требованиями", и уровень доступности должен прописываться в техническом задании в ограничениях про проекту, т.к. не очень понятно какова реально аудитория с проблемами и целесообразно ли экономически поддерживать подобное в проекте, всё это решать не разработчикам, а аналитикам, архитекторам и продакту. 

Таким образом, если видишь такие "нефункциональные" возможности по улучшению, то всегда их подсвечивай, но никогда не принимай решения сам. К аналогичным "нефункциональным требованиям" можно отнести: оптимизации, поддержку браузеров, языков и т.д.

P.S. Отвечая на вопрос: "пока не нашёл как проверять подключение самого компонента без поиска конкретных элементов в отрендеренном DOM", к сожалению, никак... но если вдруг способ найдёшь - напиши :)

2023-02-07 19:54 UTC, practicum-maxim-zyryanov requested changes
Нормальное решение, но мне не нравится повсеместное нарушение DRY в коде и логика раскиданная по разным компонентам, и здесь прошу @Sasha-meow дополнительно пройтись по комментариям, и решить (с точки зрения команды), что из этого правите сейчас, что игнорируете, а что выносите в задачи на будущее

2023-02-07 19:54 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/ForumPage/ForumPage.test.tsx
> +});
DRY - справедлив и для тестов, а схожих фрагментов кода в пулреквесте не мало, ряд базовых проверок вполне можно обернуть в некоторый shared test

2023-02-07 19:54 UTC, practicum-maxim-zyryanov commented on packages/client/src/features/auth/logIn.ts
> +export const logIn = () => localStorage.setItem("isLogged", LS_isLogged.YES);
По опыту могу сказать, что держать логику входа и выхода в разных компонентах - не очень, т.к. они часто предполагают совместные изменения. К примеру, даже здесь, если поменяется название ключа, то его потребуется менять и в logOut.ts. 

Рекомендую вынести логику входа / выхода в отдельный класс бизнес-логики, в классе определить ключ как константу (которую можно легко модифицировать в одном месте, а не искать по всему коду), а в компонентах уже вызывать условно `auth.login()` и `auth.logout()`

2023-02-07 19:54 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/ForumPage/ForumPage.tsx
> +    </main>
Как-то много нахожу таких фрагментов... возможно всё ок, и по смыслу они разойдутся далее, а возможно здесь не хватает компонента враппера, ответственного за отображение хедера... на вывод такого компонента и тест можно написать всего один, а не множество... просто призываю подумать о дальнейшем развитии

2023-02-07 19:54 UTC, practicum-maxim-zyryanov commented on packages/client/src/router/Router.test.tsx
> +    });
DRY!

2023-02-07 19:54 UTC, practicum-maxim-zyryanov commented on packages/client/src/router/modes/GuestMode/GuestMode.tsx
> +export const GuestMode: FC<PrivateModeProps> = ({ children }) => {
Разнесение логики проверки авторизации по двум компонентам действительно вызывает вопросы, но пока так быстро не соображу, что здесь посоветовать, чтобы не сломать заложенную логику.

2023-02-08 12:20 UTC, ArtificialMan3000 commented on packages/client/src/router/modes/GuestMode/GuestMode.tsx
> +export const GuestMode: FC<PrivateModeProps> = ({ children }) => {
Тут идея в том, что если надо запредить доступ к странице неавторизованным - оборачиваем её в PrivateMode, а если надо запретить доступ авторизованным - оборачиваем в GuestMode

2023-02-08 12:27 UTC, ArtificialMan3000 commented on packages/client/src/pages/ForumPage/ForumPage.test.tsx
> +});
В предыдущем модуле на вебинаре говорили, что тесты должны быть максимально простыми, без сложной логики и циклов. Поэтому я и продублировал код в тестах. Я предлагаю оставить пока так и отложить рефакторинг тестов до модуля, где будет задача на тесты.

2023-02-08 12:46 UTC, Sasha-meow commented on packages/client/src/pages/ForumPage/ForumPage.test.tsx
> +});
Да, но также говорили еще (не знаю как у вас, а у нас такое было) на вебинарах, что можно и нужно создавать что-то по типу функций-фабрик для генерирования однотипных тестов - и это считается best practise, так сказать.
Я предлагаю вообще пока тесты выпилить в таком случае, и писать хорошо и по канонам в следующем модуле после теории про jest @ArtificialMan3000

2023-02-08 12:50 UTC, ArtificialMan3000 commented on packages/client/src/features/auth/logIn.ts
> +export const logIn = () => localStorage.setItem("isLogged", LS_isLogged.YES);
Ключ вынес в shared константы, т.к. он ещё используется в хуке useAuth. Функции перенёс в общий файл. Класс пока делать не стал, т.к. ещё неизвестно как это будет в будущем организовано. Это же поидее будут экшены редакса.

2023-02-08 12:56 UTC, ArtificialMan3000 commented on packages/client/src/pages/ForumPage/ForumPage.tsx
> +    </main>
У нас уже есть компонент BasicLayout от Александры. Каждый, когда будет делать свою страницу заменит это на использование этого компонента.

2023-02-08 12:57 UTC, ArtificialMan3000 commented on packages/client/src/router/Router.test.tsx
> +    });
Об этом прокомментировал выше

2023-02-08 12:59 UTC, Sasha-meow commented on packages/client/src/router/modes/GuestMode/GuestMode.tsx
> +export const GuestMode: FC<PrivateModeProps> = ({ children }) => {
Давай пока это оставим, сейчас без прикрученной авторизации и редакса мало, что сделаешь. В дальнейшем в рамках [задачи про HOC](https://linear.app/cosmostars/issue/COS-59/realizaciya-hoc-a-proverki-avtorizacii) из следующего спринта - оставим только один PrivateMode, там уже и редакс будет и авторизация прикручена - нормально обработаем. В конце недели изучу вопрос и эту задачу побольше

2023-02-08 15:21 UTC, ArtificialMan3000 commented on packages/client/src/pages/ForumPage/ForumPage.test.tsx
> +});
Вот сейчас вспомнил, что у нас тоже упоминали об этом, но очень вскользь) Ладно, уберу пока тесты, чтобы время не тратить сейчас.

2023-02-08 16:41 UTC, practicum-maxim-zyryanov approved these changes
Approve, но просьба убедиться, что по всем допущениям заведены таски в linear.app (банально чтобы не забыть про это)

2023-02-09 05:05 UTC, merged