COS-67: Доработать функционал загрузки аватара
CosmoStarz/cosmostars pull request #31
Opened 2023-03-09 19:59 UTC by zomkd

### Какую задачу решаем
Добавлена возможность загрузки фотографии с помощью drag and drop, а также превью загруженной картинки

Для проверки нужно зайти на страницу редактирования профиля, загрузить фотографии с помощью drag and drop или с помощью выбор файла. 
Фотография сохраняется при нажатии кнопки Save

2023-03-10 16:11 UTC, Sasha-meow requested changes
Круто сделал, появилось красивое превью! Но есть пару замечаний, по картинке особенно исправить надо

2023-03-10 18:03 UTC, Sasha-meow commented on packages/client/src/features/Profile/change-avatar/ui.tsx
> +  const [oldAvatar, setOldAvatar] = useState<string>("");
Тут можно обойтись без этого useState. Если его убрать - поведение не поменяется, а код станет понятнее

2023-03-10 18:15 UTC, zomkd commented on packages/client/src/features/Profile/change-avatar/ui.tsx
> +                  backgroundColor: "rgba(255,255,255,0.1)",
При drag and drop меняется цвет области и надпись, это для этого

2023-03-10 18:22 UTC, zomkd commented on packages/client/src/features/Profile/change-avatar/ui.tsx
> +  const [oldAvatar, setOldAvatar] = useState<string>("");
Это влияет на то, что при нажатия крестика на картинке, остаётся старая фотография

2023-03-12 06:24 UTC, Sasha-meow commented on packages/client/src/features/Profile/change-avatar/ui.tsx
> +                        backgroundPosition: "center",
здесь можно некоторые поля засунуть в одно и обойтись общим свойством [background](https://developer.mozilla.org/en-US/docs/Web/CSS/background)

2023-03-12 06:24 UTC, Sasha-meow commented on packages/client/src/features/Profile/change-avatar/ui.tsx
> +                        width: 100,
а почему именно 100 на 130? Там же места полно остается
![image](https://user-images.githubusercontent.com/72806681/224528057-f1c6f739-de80-4888-8f47-561e500483d4.png)

2023-03-12 06:29 UTC, Sasha-meow approved these changes
все оки, будет круто, если свойства в одно засунешь, но на аппрув не влияет

2023-03-13 16:41 UTC, practicum-maxim-zyryanov approved these changes

2023-03-13 18:25 UTC, merged