COS-66 Notification
CosmoStarz/cosmostars pull request #33
Opened 2023-03-11 14:10 UTC by ArtificialMan3000

Внедрены уведомления об ошибках в запросах к API. При неудачном запросе в левом нижнем углу вылазит красная плашка с текстом ошибки и исчезает через 6 секунд.

![image](https://user-images.githubusercontent.com/16936575/224489336-a63dc4c6-aa24-47f0-a867-1a7735951e6e.png)

2023-03-11 18:03 UTC, Sasha-meow requested changes
Все клево, но надо поправить некоторые текстовки, описала ниже
Кроме того, выявились ошибки парсинга некоторых запросов с яндекс апи - надо будет поправить, но, наверное, отдельной задачкой

2023-03-13 12:44 UTC, ArtificialMan3000 commented on packages/client/src/entities/notification/notificationSlice.ts
> +  text: "";
Нет, исправил

2023-03-13 12:46 UTC, ArtificialMan3000 commented on packages/client/src/pages/sign-in/index.tsx
> +      <Notification />
Перенёс

2023-03-13 12:51 UTC, ArtificialMan3000 commented on packages/client/src/widgets/Notification/Notification.tsx
> +          open={true}
Мне так кажется более понятно. Если в начале стоит is, то сразу ясно, что это булевый тип. Кроме того, здесь по смыслу больше shown подходит, т.к. снекбар всегда open)

2023-03-13 13:03 UTC, ArtificialMan3000 commented on packages/client/src/entities/notification/notificationMiddleware.ts
> +          text: action.payload,
Исправил

2023-03-13 13:04 UTC, ArtificialMan3000 commented on packages/client/src/widgets/Notification/Notification.tsx
> +            {String(text)}
Поправил

2023-03-13 18:36 UTC, Sasha-meow approved these changes

2023-03-15 15:42 UTC, practicum-maxim-zyryanov approved these changes

2023-03-15 15:51 UTC, merged