COS-75: Метод обновления данных лидерборда
CosmoStarz/cosmostars pull request #35
Opened 2023-03-13 16:51 UTC by tacticSugar

### Прикрутил метод обновления данных лидерборда

2023-03-13 18:53 UTC, Sasha-meow requested changes

2023-03-13 18:53 UTC, Sasha-meow commented on packages/client/src/widgets/GameModal/GameModal.tsx
> +  console.log(data);
лишние логи давай уберем

2023-03-13 18:53 UTC, Sasha-meow commented on packages/client/src/widgets/GameModal/GameModal.tsx
> +    if (id && nameForLeaderboard && avatar) {
аватар может быть undefined, проверка лишняя

2023-03-13 18:53 UTC, Sasha-meow commented on packages/client/src/widgets/GameModal/GameModal.tsx
> +      addLeaderboardEntry({
Данные отправляются и при инициализации игры, когда нажимаешь кнопку "start" и при паузе, когда жмешь "resume". Данные тут надо отсылать только если ты проиграл и нажимаешь "try again" (напрашивается проверка на статус LOOSE)

2023-03-13 18:53 UTC, Sasha-meow commented on packages/client/src/widgets/Leaderboard/Leaderboard.tsx
> -      addLeaderboardEntry({ ...generateRandomUserInfo(), score });
Думаю лишние оставшиеся функции нужно убрать, они тут больше не используются. Строка 15, 12, 2 и 1 - выборочно

2023-03-15 05:52 UTC, Sasha-meow commented on packages/client/src/widgets/GameModal/GameModal.tsx
> +    if (id && nameForLeaderboard && avatar) {
Это не исправлено. У нас юзер может быть без аватарки, это не причина не сохранять результат его игры

2023-03-19 03:57 UTC, practicum-maxim-zyryanov approved these changes

2023-03-19 04:20 UTC, merged