COS-27: OAuth
CosmoStarz/cosmostars pull request #37
Opened 2023-03-13 20:30 UTC by zomkd

### Какую задачу решаем
добавил авторизацию OAuth через Яндекс
на старнице логина добавлен кнопка Yandex, через нее можно авторизоваться

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-03-14 18:17 UTC, Sasha-meow requested changes
Ты молодец, все хорошо работает!
Ноооо запрос четырехразовый и кнопку точно нужно поправить

2023-03-14 18:17 UTC, Sasha-meow commented on packages/client/src/features/Auth/YanedxOAuth/ui.tsx
> +    async function yandexOauth() {
Может эту функцию вообще вынести можно? А то слишком громоздко + надо разобраться, почему запросы делаются по 4 раза:
![image](https://user-images.githubusercontent.com/72806681/225096500-a867bafa-6f88-4030-8405-91216c571143.png)

2023-03-14 18:17 UTC, Sasha-meow commented on packages/client/src/features/Auth/YanedxOAuth/ui.tsx
> +        if (data === OK_RESPONSE) {
эта проверка не особо хорошая: во-первых к строкам привязываемся - если в апи ответ изменят на "ОК, босс" - то у нас выкинет ошибку, а в ошибке выкинет ошибку, что ошибки нет
Во-вторых, если запрос упал - то data вообще не придет, только error
Короче можно просто сделать `if (data)`, это работать должно

2023-03-14 18:17 UTC, Sasha-meow commented on packages/client/src/features/Auth/YanedxOAuth/ui.tsx
> +    <IconButton
Так, а почему у нас в IconButton текст? Этот тег априори должен включать в себя иконку или картинку
Давай заюзаем простой `<Button/>` и целиком кнопку озаглавим Enter with yandex

2023-03-14 18:24 UTC, Sasha-meow commented on packages/client/src/features/Auth/YanedxOAuth/ui.tsx
> +    async function yandexOauth() {
Там еще страница логина мелькает либо один, либо иногда по два раза туда-сюда при успешной авторизации через яндекс. Может если редирект на главную делать - меньше мелькать будет? Ну это просто предположение

2023-03-21 05:37 UTC, practicum-maxim-zyryanov approved these changes
Некоторые методы возможно стоило бы разбить на несколько более коротких, текстовые строки вынести в константы и провести ряд прочих мелких улучшений, но пока авторизация обособлена в отдельном месте это совсем не критично

2023-03-21 06:21 UTC, merged