COS-85 Create topic api
CosmoStarz/cosmostars pull request #49
Opened 2023-03-28 15:38 UTC by ArtificialMan3000

Добавлено новое апи "internalApi" для форума. Создан эндпойнт для добавления нового топика и привязан к кнопке "ADD +" в интерфейсе.
При добавлении топика должен отправляться запрос на localhost:3001 (baseUrl) в формате описанном [здесь](https://linear.app/cosmostars/issue/COS-85/prikrutit-api-sozdaniya-topika)

2023-03-29 03:43 UTC, Sasha-meow requested changes

2023-03-29 03:43 UTC, Sasha-meow commented on packages/client/src/entities/forum/topics/api/types/frontend.ts
> +  authorId: number;
с фронта надо отправлять данные соответственно с author_id

2023-03-29 03:43 UTC, Sasha-meow commented on packages/client/src/features/AddTopic/AddTopic.tsx
> +      onSubmit({ title: topicName, description: topicDescription, authorId });
Еще бы хорошо закрывать эту модалку при успешном создании

2023-03-29 03:50 UTC, Sasha-meow commented on packages/client/package.json
> +    "dev": "vite --host",
а это точно нужно?

2023-03-29 09:29 UTC, ArtificialMan3000 commented on packages/client/src/entities/forum/topics/api/types/frontend.ts
> +  authorId: number;
Поправил

2023-03-29 09:37 UTC, ArtificialMan3000 commented on packages/client/src/features/AddTopic/AddTopic.tsx
> +      onSubmit({ title: topicName, description: topicDescription, authorId });
Добавил закрытие

2023-03-29 09:40 UTC, ArtificialMan3000 commented on packages/client/package.json
> +    "dev": "vite --host",
Когда следущую задачу буду делать ещё раз попробую без этого, если всё будет норм, удалю.

2023-03-29 10:23 UTC, ArtificialMan3000 commented
Запрос на localhost:3001 кстати блочится CORSом, надо будет на сервере разрешить запросы с localhost:3000

2023-03-29 16:16 UTC, Sasha-meow approved these changes

2023-03-30 05:58 UTC, ArtificialMan3000 commented
localhost:3001 существует. На preflight запросе приходит отказ из-за cors и 'рабочий' запрос блокируется браузером. Chrome dev tools префлайты не показывает, но всё равно пишет, что проблема с cors. А вот firefox покажет префлайт, можешь там посмотреть.

2023-04-01 18:23 UTC, Sasha-meow commented
@ArtificialMan3000 , надо вмержить сюда дев и решить конфликты

2023-04-04 06:18 UTC, merged