COS-100 - Прикрутить api топиков, топика, комментов
CosmoStarz/cosmostars pull request #55
Opened 2023-04-02 11:27 UTC by tacticSugar

Добавлены запросы на получение топиков, топика и комментов.
Данные получены и обработаны на страницах

2023-04-03 05:29 UTC, Sasha-meow requested changes
Требуются правки + тесты не проходят из-за той злосчастной строки
Более того, я попросила тебя перед тем, как зальешь, чтобы в описании ссылался на две задачи, чтобы linear их подтянул.

2023-04-03 05:29 UTC, Sasha-meow commented on MEMORYLEAKS.md
> +<a href="https://ibb.co/zVvSHSs"><img src="https://i.ibb.co/zVvSHSs/photo-2023-03-26-14-07-33.jpg" alt="photo-2023-03-26-14-07-33" border="0"></a>
это отдельная задача, в этой ветке она не нужна. Как и форум в ветке с утечками

2023-04-03 05:29 UTC, Sasha-meow commented on packages/client/src/widgets/Forum/Forum.tsx
> +          count={data ? data.count : 1}
А если у нас 0 комментариев приходит? выводиться будет все равно 1

2023-04-03 05:29 UTC, Sasha-meow commented on packages/client/src/widgets/Forum/Forum.tsx
>            rowsPerPageOptions={[1, 2, 3]}
Может побольше сделаем, что ли...а то один топик в списке вообще грустно смотрится. Давай поменяем на 3 - 6 - 9 хотя бы

2023-04-03 05:29 UTC, Sasha-meow commented on packages/client/src/widgets/Forum/Forum.tsx
> +                        Topic {topic.title}
тут по логике надо оставить только topic.title

2023-04-03 05:29 UTC, Sasha-meow commented on packages/client/src/shared/api/baseForumApi.ts
> +  reducerPath: "forumApi",
дубль internalApi, убираем

2023-04-03 05:29 UTC, Sasha-meow commented on packages/client/src/pages/ForumTopicPage/ForumTopicPage.tsx
> +    navigate('/not-found')
надо сделать yarn format - скобки не те
этот урл у тебя есть в константах, это хорошо, поэтому заменяем волшебную строку на константу

2023-04-03 05:29 UTC, Sasha-meow commented on packages/client/src/pages/ForumTopicPage/ForumTopicPage.tsx
> +  const forumId: number = +currentUrl.pathname.match("[^/]+$")![0];
Надо все равно как-то побороть эту историю: eslint ругается + ошибки могут быть запросто

2023-04-04 06:16 UTC, Sasha-meow commented
Перехватила задачу по согласованию
В рамках данной ветки реализовано две задачи, так как они оказались тесно взаимосвязаны. Логика работы предельно проста: при переходе на страницу форума запрашивается список топиков. При переходе на детальную страницу топика - берется id из урла (с обработкой ошибок) и по id запрашивается нужный топик и комментарии к топику. Если такого топика не существует или id невалидный - пользователя редиректит на страницу ошибки. Прикрутили лоадер, когда ожидаем ответ от сервера
В рамках задачи сделала:
Исправила замечания по ревью, добавила хук useTopic для обработки запросов, чтобы данную логику не плодить в компоненте, исправила ругань линтера на некорректное извлечение id форума

2023-04-04 06:17 UTC, Sasha-meow approved these changes

2023-04-07 09:13 UTC, practicum-maxim-zyryanov approved these changes
И здесь мне в том числе понравилось как отработали ревью внутри

2023-04-07 09:13 UTC, practicum-maxim-zyryanov commented on packages/client/src/widgets/Forum/Forum.tsx
> +  const [rowsPerPage, setRowsPerPage] = useState(3);
```
<TablePagination
          component="div"
          rowsPerPageOptions={[3, 5, 10]}
```

Здесь возможно стоило бы вынести массив, чтобы сослаться на массив в TablePagination, и на первый элемент в useState. Тогда при изменении списка значений не потребуется менять код, достаточно поменять массив в объекте-конфигруации.

2023-04-07 09:27 UTC, merged