[COS-83]: Реализация контроллера топиков
CosmoStarz/cosmostars pull request #56
Opened 2023-04-02 21:31 UTC by littox

### Какую задачу решаем
Реализация контроллера топиков

в качестве валидатора используется https://express-validator.github.io/docs/
пример ответа при невалидном ответе
`{
    "errors": [
        {
            "msg": "title - минимум 2 символа",
            "param": "title",
            "location": "body"
        },
        {
            "msg": "description - минимум 2 символа",
            "param": "description",
            "location": "body"
        }
    ]
}`

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-04-03 05:06 UTC, Sasha-meow requested changes
Классно, что валидацию сделал, вроде и по задаче необязательно было. Выглядит все прекрасно
Пару моментов поправить только

2023-04-03 05:06 UTC, Sasha-meow commented on packages/server/middlewares/validation.ts
> +    res.status(400).json({ errors: errors.array() });
Если автора не указываешь - сообщение задваивается
![image](https://user-images.githubusercontent.com/72806681/229415490-0173bfd5-6032-4c22-aac0-54757ab4b741.png)

2023-04-03 05:06 UTC, Sasha-meow commented on packages/server/routes/TopicRoutes.ts
> +    body("author_id", "author_id - только числовой id").exists().isNumeric(),
Возможно, кстати, причина в том, что тут две проверки

2023-04-03 22:23 UTC, littox commented on packages/server/routes/TopicRoutes.ts
> +    body("author_id", "author_id - только числовой id").exists().isNumeric(),
Да, именно в этом причина

2023-04-03 22:24 UTC, littox commented on packages/server/controllers/TopicController.ts
> +  return res.status(200).json(topic);
Сделал мидлваре. В случае если параметр не числовой - соответственно в базе не будет записи -> 404.

2023-04-04 04:18 UTC, Sasha-meow approved these changes
Шикарно

2023-04-07 08:53 UTC, practicum-maxim-zyryanov approved these changes

2023-04-07 09:05 UTC, merged