COS-90: Закрыть "ручки" за авторизацией
CosmoStarz/cosmostars pull request #59
Opened 2023-04-06 20:16 UTC by zomkd

### Какую задачу решаем
сделать так, чтобы роуты с бекенда были доступны только авторизированных пользователей

2023-04-07 07:32 UTC, Sasha-meow requested changes
Круто вышло, но типы сто процентов поправить надо, чтоб у нас ничего не отвалилось

2023-04-07 07:32 UTC, Sasha-meow commented on packages/client/src/shared/config/index.ts
> +// export const API_URL = "https://ya-praktikum.tech/api/v2";
Наверное, эта строка нам больше не нужна

2023-04-07 07:32 UTC, Sasha-meow commented on packages/server/middlewares/checkAuth.ts
> +  login: string;
Может тип вынесем в отдельный файлик, чтоб красиво было?

2023-04-07 07:32 UTC, Sasha-meow commented on packages/server/middlewares/checkAuth.ts
> +  avatar: null;
тут может быть string | null

2023-04-07 07:32 UTC, Sasha-meow commented on packages/server/middlewares/checkAuth.ts
> +  phone: string;
Тут вроде тоже. Ты на фронте недавно правил

2023-04-07 07:32 UTC, Sasha-meow commented on packages/server/middlewares/checkAuth.ts
> +          error: e.response?.data?.reason ?? e.message,
У нас общий формат ошибки reason в формате application/json, не в текстовом
И для их формирования написана специальная функция - configureError в папке utils - ее можно заюзать

2023-04-07 07:32 UTC, Sasha-meow commented on packages/server/middlewares/checkAuth.ts
> +        .status(e.status ?? 401)
401 давай вынесем в enum константы со статусами. В файле constants лежат

2023-04-07 07:32 UTC, Sasha-meow commented on packages/server/routes/ThemeRoutes.ts
> +themeRouter.get("/:id", getThemeByUser).post("/:id", createThemeToUser);
А тут обязательно все в одну строку переводить? Мне казалось, первичный вариант был более читабельным что ли..ну это лично на мой вкус и цвет, просто спрашиваю
У нас и в топиках и в комментах они разделены

2023-04-07 09:27 UTC, zomkd commented on packages/server/routes/ThemeRoutes.ts
> +themeRouter.get("/:id", getThemeByUser).post("/:id", createThemeToUser);
Да особо нет, просто как сокращение решил использовать, раз возможность есть )

2023-04-09 07:07 UTC, Sasha-meow reviewed
Все проверено - работает отлично! Ты умничка
![image](https://user-images.githubusercontent.com/72806681/230759387-85298edf-a470-4c6d-b063-8ce182f5fc64.png)
![image](https://user-images.githubusercontent.com/72806681/230759411-b93e55b9-9d0a-4dd8-8ba5-485880450793.png)

2023-04-09 07:09 UTC, Sasha-meow commented
Надо еще подключить к этой мидлваре и комменты, как вольем в дев

2023-04-10 04:30 UTC, Sasha-meow approved these changes
Все отлично!

2023-04-11 08:53 UTC, merged