COS-14: Авторизация и регистрация
CosmoStarz/cosmostars pull request #7
Opened 2023-02-10 17:35 UTC by zomkd

### Какую задачу решаем
Создал страницы для логина и авторизации

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-02-10 20:02 UTC, Sasha-meow requested changes
Посмотрела, решение работает, но с некоторыми багами - ниже оставила замечания
Особенно выделяется форматирование (сделай yarn format перед тем, как будешь заливать)

2023-02-10 21:35 UTC, zomkd commented on packages/client/src/features/Password/ui.tsx
> +import { PropsWithChildren } from "react";
это к следующей задаче)

2023-02-11 17:59 UTC, Sasha-meow commented on packages/client/src/shared/ui/Card/index.tsx
> +                    endAdornment: field.type ==='password' && <InputAdornment position="end">
Баг не исправлен, просто из второго поля исчезла эта иконка (но там она предполагается)
![image](https://user-images.githubusercontent.com/72806681/218273502-7ceeefad-bd4c-4fc3-be55-0f7d21000afb.png)

2023-02-11 18:14 UTC, Sasha-meow approved these changes
Есть момент над которым будем думать - со скрытием/открытием паролей, в остальном все рабочее, многое исправлено

2023-02-13 09:39 UTC, practicum-maxim-zyryanov approved these changes
Хорошее решение, ничего критичного сейчас не вижу

2023-02-13 09:39 UTC, practicum-maxim-zyryanov commented on packages/client/src/features/Auth/schemas/consts.ts
> +    /^((\\+[1-9]{1,4}[ \\-]*)|(\\([0-9]{2,3}\\)[ \\-]*)|([0-9]{2,4})[ \\-]*)*?[0-9]{3,4}?[ \\-]*[0-9]{3,4}?$/,
Используете camelCase или всё же капс?

2023-02-13 10:32 UTC, Sasha-meow commented on packages/client/src/features/Auth/schemas/consts.ts
> +    /^((\\+[1-9]{1,4}[ \\-]*)|(\\([0-9]{2,3}\\)[ \\-]*)|([0-9]{2,4})[ \\-]*)*?[0-9]{3,4}?[ \\-]*[0-9]{3,4}?$/,
Вообще CamelCase, но капсом тоже пользуемся в enum, например..тут просто Игорь забыл поправить, договорились поправить в рамках рефактора

2023-02-13 10:38 UTC, merged