Feature/cos 16 leaderboard page
CosmoStarz/cosmostars pull request #9
Opened 2023-02-11 17:59 UTC by ArtificialMan3000

Сверстал страницу лидерборда. Апи пока подключать не стал.

2023-02-11 18:47 UTC, Sasha-meow requested changes
Классно сделал! Мне очень понравилось разделение компонент на более мелкие, прям хорошее
Но есть несколько важных замечаний, основные - по стилям в общеиспользуемых компонентах

2023-02-11 18:47 UTC, Sasha-meow commented on packages/client/src/pages/LeaderboardPage/LeaderboardPage.tsx
> +      <Container sx={{ mt: "135px", mb: "93px" }}>
С точки зрения адаптивности лучше пользоваться относительными единицами измерения. Да и вообще это считается хорошей практикой.
Понятно, что сейчас прямой задачи на адаптивность нет, но может и появиться, и тогда относительные единицы нам очень помогут)

2023-02-11 18:47 UTC, Sasha-meow commented on packages/client/src/shared/layouts/BasicLayout.tsx
> +        minHeight: "100vh",
При разработке своего отдельного компонента и использовании при этом общеиспользуемых компонентов лучший вариант - не вносить правки во второе, так как данная махинация может что-либо сломать.
Но если выбора нет и вносишь правки в общеиспользуемое - после этого стоит ВСЕГДА проверять, а не поехала ли верстка в других разделах? Вот конкретно данное изменение повлияло на другие страницы приложения. Лучше так не делать
Конкретно в твоем случае можно уменьшить количество строк в таблице на странице или/и добавить туда скролл

2023-02-11 18:47 UTC, Sasha-meow commented on packages/client/src/index.css
> +  /* overflow: hidden; */
Та же самая история - свойство добавили не просто так, а значит что-то где-то может поехать (уже поехало)

2023-02-11 18:47 UTC, Sasha-meow commented on packages/client/src/widgets/Leaderboard/Leaderboard.tsx
> +          fontFamily: "Bubblegum Sans",
Шрифт по умолчанию на этот установлен, тут его объявление и прописание всех свойств - излишне

2023-02-11 18:47 UTC, Sasha-meow commented on packages/client/src/widgets/Leaderboard/Leaderboard.tsx
> +        pb: "75px",
общее свойство для pr pl - py

2023-02-11 18:47 UTC, Sasha-meow commented on packages/client/src/widgets/Leaderboard/ui/types.ts
> +  status: "online" | "offline";
"online" и "offline" можно вынести в отдельный enum, чтобы не было волшебных строк. Также и в моки пока что передавать можно

2023-02-11 18:47 UTC, Sasha-meow commented on lerna-debug.log
> +3 error     at resolve (/home/alexander/ya.practicum/cosmostars/node_modules/npm-package-arg/npa.js:84:12)
Это что за чудо файл такой

2023-02-12 08:19 UTC, ArtificialMan3000 commented on packages/client/src/pages/LeaderboardPage/LeaderboardPage.tsx
> +      <Container sx={{ mt: "135px", mb: "93px" }}>
А какие лучше здесь использовать? Я просто всегда на пикселях верстал.

2023-02-12 08:43 UTC, ArtificialMan3000 commented on packages/client/src/widgets/Leaderboard/Leaderboard.tsx
> +          fontFamily: "Bubblegum Sans",
Убрал

2023-02-12 08:45 UTC, ArtificialMan3000 commented on packages/client/src/widgets/Leaderboard/Leaderboard.tsx
> +        pb: "75px",
Поменял

2023-02-12 08:49 UTC, ArtificialMan3000 commented on packages/client/src/widgets/Leaderboard/ui/types.ts
> +  status: "online" | "offline";
Поправил

2023-02-12 08:52 UTC, ArtificialMan3000 commented on lerna-debug.log
> +3 error     at resolve (/home/alexander/ya.practicum/cosmostars/node_modules/npm-package-arg/npa.js:84:12)
Добавил в .gitignore

2023-02-12 08:53 UTC, Sasha-meow commented on packages/client/src/pages/LeaderboardPage/LeaderboardPage.tsx
> +      <Container sx={{ mt: "135px", mb: "93px" }}>
@ArtificialMan3000 : % (рассчитывается относительно родителя),  vh vw (относительно экрана),а также em (относительно шрифта родителя) rem (относительно шрифта корневого элемента). 
В интернете много неплохих статей на эту тему, разберёшься быстро , я же оставлю ссылку на [классику](https://learn.javascript.ru/css-units)

2023-02-13 11:19 UTC, ArtificialMan3000 commented on packages/client/src/pages/LeaderboardPage/LeaderboardPage.tsx
> +      <Container sx={{ mt: "135px", mb: "93px" }}>
Внёс правки

2023-02-13 11:20 UTC, ArtificialMan3000 commented on packages/client/src/shared/layouts/BasicLayout.tsx
> +        minHeight: "100vh",
Сделал как договорились

2023-02-13 12:58 UTC, practicum-maxim-zyryanov approved these changes

2023-02-13 12:58 UTC, practicum-maxim-zyryanov commented on packages/client/src/widgets/Leaderboard/Leaderboard.tsx
> +  },
Хорошее решение вынести всё в отдельный массив, и далее не акцентировать внимание на работу с моком,  но рекомендовал бы такие куски вообще выносить в отдельный объект, и получать данные где-нибудь в методе инициализации через `leaderboardData = api.getLeaderboardDate()`, так в файле вообще не останется намёка на мок, а кроме того в коде будет сразу реализована и логика получения данных, что позволит далее не вносить изменения в этот файл, а просто изменить реализацию метода `getLeaderboardData`

2023-02-13 14:32 UTC, ArtificialMan3000 commented on packages/client/src/widgets/Leaderboard/Leaderboard.tsx
> +  },
Вынес в папку data, т.к. неизвестно ещё какое апи будет в дальнейшем (скорее всего через useSelector)

2023-02-13 14:33 UTC, merged